version: 1.7.0-{branch}{build}
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
  - ci-preparations
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
- ARM
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 1.7.0.{build}
  assembly_file_version: 1.7.0.{build}
  assembly_informational_version: 1.7.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: '& ".\AfterBuild.ps1"'
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
deploy:
- provider: Environment
  name: MyGet
- provider: Environment
  name: NuGet
  on:
    branch: master
- provider: Environment
  name: GitHub Releases
  on:
    branch: master
